[theme]
primaryColor = "#38BDF8"
backgroundColor = "#0D0F12"
secondaryBackgroundColor = "#161B22"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
